/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedMinhaRotinaRouteImport } from './routes/_authenticated/minha-rotina'
import { Route as AuthenticatedKanbanRouteImport } from './routes/_authenticated/kanban'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedAdminMetricasRouteImport } from './routes/_authenticated/admin-metricas'
import { Route as AuthenticatedNpsIndexRouteImport } from './routes/_authenticated/nps.index'
import { Route as AuthenticatedClientesIndexRouteImport } from './routes/_authenticated/clientes.index'
import { Route as NpsFormSlugRouteImport } from './routes/nps.form.$slug'
import { Route as AuthenticatedNpsRespostasRouteImport } from './routes/_authenticated/nps.respostas'
import { Route as AuthenticatedNpsLinksRouteImport } from './routes/_authenticated/nps.links'
import { Route as AuthenticatedNpsDetratoresRouteImport } from './routes/_authenticated/nps.detratores'
import { Route as AuthenticatedClientesClienteIdRouteImport } from './routes/_authenticated/clientes.$clienteId'
import { Route as ApiPublicHooksNpsRouteImport } from './routes/api/public/hooks/nps'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMinhaRotinaRoute =
  AuthenticatedMinhaRotinaRouteImport.update({
    id: '/minha-rotina',
    path: '/minha-rotina',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedKanbanRoute = AuthenticatedKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminMetricasRoute =
  AuthenticatedAdminMetricasRouteImport.update({
    id: '/admin-metricas',
    path: '/admin-metricas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNpsIndexRoute = AuthenticatedNpsIndexRouteImport.update({
  id: '/nps/',
  path: '/nps/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientesIndexRoute =
  AuthenticatedClientesIndexRouteImport.update({
    id: '/clientes/',
    path: '/clientes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const NpsFormSlugRoute = NpsFormSlugRouteImport.update({
  id: '/nps/form/$slug',
  path: '/nps/form/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNpsRespostasRoute =
  AuthenticatedNpsRespostasRouteImport.update({
    id: '/nps/respostas',
    path: '/nps/respostas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNpsLinksRoute = AuthenticatedNpsLinksRouteImport.update({
  id: '/nps/links',
  path: '/nps/links',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNpsDetratoresRoute =
  AuthenticatedNpsDetratoresRouteImport.update({
    id: '/nps/detratores',
    path: '/nps/detratores',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientesClienteIdRoute =
  AuthenticatedClientesClienteIdRouteImport.update({
    id: '/clientes/$clienteId',
    path: '/clientes/$clienteId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicHooksNpsRoute = ApiPublicHooksNpsRouteImport.update({
  id: '/api/public/hooks/nps',
  path: '/api/public/hooks/nps',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/admin-metricas': typeof AuthenticatedAdminMetricasRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/kanban': typeof AuthenticatedKanbanRoute
  '/minha-rotina': typeof AuthenticatedMinhaRotinaRoute
  '/clientes/$clienteId': typeof AuthenticatedClientesClienteIdRoute
  '/nps/detratores': typeof AuthenticatedNpsDetratoresRoute
  '/nps/links': typeof AuthenticatedNpsLinksRoute
  '/nps/respostas': typeof AuthenticatedNpsRespostasRoute
  '/nps/form/$slug': typeof NpsFormSlugRoute
  '/clientes/': typeof AuthenticatedClientesIndexRoute
  '/nps/': typeof AuthenticatedNpsIndexRoute
  '/api/public/hooks/nps': typeof ApiPublicHooksNpsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/admin-metricas': typeof AuthenticatedAdminMetricasRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/kanban': typeof AuthenticatedKanbanRoute
  '/minha-rotina': typeof AuthenticatedMinhaRotinaRoute
  '/': typeof AuthenticatedIndexRoute
  '/clientes/$clienteId': typeof AuthenticatedClientesClienteIdRoute
  '/nps/detratores': typeof AuthenticatedNpsDetratoresRoute
  '/nps/links': typeof AuthenticatedNpsLinksRoute
  '/nps/respostas': typeof AuthenticatedNpsRespostasRoute
  '/nps/form/$slug': typeof NpsFormSlugRoute
  '/clientes': typeof AuthenticatedClientesIndexRoute
  '/nps': typeof AuthenticatedNpsIndexRoute
  '/api/public/hooks/nps': typeof ApiPublicHooksNpsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/admin-metricas': typeof AuthenticatedAdminMetricasRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/kanban': typeof AuthenticatedKanbanRoute
  '/_authenticated/minha-rotina': typeof AuthenticatedMinhaRotinaRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/clientes/$clienteId': typeof AuthenticatedClientesClienteIdRoute
  '/_authenticated/nps/detratores': typeof AuthenticatedNpsDetratoresRoute
  '/_authenticated/nps/links': typeof AuthenticatedNpsLinksRoute
  '/_authenticated/nps/respostas': typeof AuthenticatedNpsRespostasRoute
  '/nps/form/$slug': typeof NpsFormSlugRoute
  '/_authenticated/clientes/': typeof AuthenticatedClientesIndexRoute
  '/_authenticated/nps/': typeof AuthenticatedNpsIndexRoute
  '/api/public/hooks/nps': typeof ApiPublicHooksNpsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin-metricas'
    | '/feed'
    | '/kanban'
    | '/minha-rotina'
    | '/clientes/$clienteId'
    | '/nps/detratores'
    | '/nps/links'
    | '/nps/respostas'
    | '/nps/form/$slug'
    | '/clientes/'
    | '/nps/'
    | '/api/public/hooks/nps'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/admin-metricas'
    | '/feed'
    | '/kanban'
    | '/minha-rotina'
    | '/'
    | '/clientes/$clienteId'
    | '/nps/detratores'
    | '/nps/links'
    | '/nps/respostas'
    | '/nps/form/$slug'
    | '/clientes'
    | '/nps'
    | '/api/public/hooks/nps'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/admin-metricas'
    | '/_authenticated/feed'
    | '/_authenticated/kanban'
    | '/_authenticated/minha-rotina'
    | '/_authenticated/'
    | '/_authenticated/clientes/$clienteId'
    | '/_authenticated/nps/detratores'
    | '/_authenticated/nps/links'
    | '/_authenticated/nps/respostas'
    | '/nps/form/$slug'
    | '/_authenticated/clientes/'
    | '/_authenticated/nps/'
    | '/api/public/hooks/nps'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  NpsFormSlugRoute: typeof NpsFormSlugRoute
  ApiPublicHooksNpsRoute: typeof ApiPublicHooksNpsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/minha-rotina': {
      id: '/_authenticated/minha-rotina'
      path: '/minha-rotina'
      fullPath: '/minha-rotina'
      preLoaderRoute: typeof AuthenticatedMinhaRotinaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kanban': {
      id: '/_authenticated/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof AuthenticatedKanbanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin-metricas': {
      id: '/_authenticated/admin-metricas'
      path: '/admin-metricas'
      fullPath: '/admin-metricas'
      preLoaderRoute: typeof AuthenticatedAdminMetricasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nps/': {
      id: '/_authenticated/nps/'
      path: '/nps'
      fullPath: '/nps/'
      preLoaderRoute: typeof AuthenticatedNpsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clientes/': {
      id: '/_authenticated/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AuthenticatedClientesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/nps/form/$slug': {
      id: '/nps/form/$slug'
      path: '/nps/form/$slug'
      fullPath: '/nps/form/$slug'
      preLoaderRoute: typeof NpsFormSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/nps/respostas': {
      id: '/_authenticated/nps/respostas'
      path: '/nps/respostas'
      fullPath: '/nps/respostas'
      preLoaderRoute: typeof AuthenticatedNpsRespostasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nps/links': {
      id: '/_authenticated/nps/links'
      path: '/nps/links'
      fullPath: '/nps/links'
      preLoaderRoute: typeof AuthenticatedNpsLinksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nps/detratores': {
      id: '/_authenticated/nps/detratores'
      path: '/nps/detratores'
      fullPath: '/nps/detratores'
      preLoaderRoute: typeof AuthenticatedNpsDetratoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clientes/$clienteId': {
      id: '/_authenticated/clientes/$clienteId'
      path: '/clientes/$clienteId'
      fullPath: '/clientes/$clienteId'
      preLoaderRoute: typeof AuthenticatedClientesClienteIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/hooks/nps': {
      id: '/api/public/hooks/nps'
      path: '/api/public/hooks/nps'
      fullPath: '/api/public/hooks/nps'
      preLoaderRoute: typeof ApiPublicHooksNpsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminMetricasRoute: typeof AuthenticatedAdminMetricasRoute
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedKanbanRoute: typeof AuthenticatedKanbanRoute
  AuthenticatedMinhaRotinaRoute: typeof AuthenticatedMinhaRotinaRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedClientesClienteIdRoute: typeof AuthenticatedClientesClienteIdRoute
  AuthenticatedNpsDetratoresRoute: typeof AuthenticatedNpsDetratoresRoute
  AuthenticatedNpsLinksRoute: typeof AuthenticatedNpsLinksRoute
  AuthenticatedNpsRespostasRoute: typeof AuthenticatedNpsRespostasRoute
  AuthenticatedClientesIndexRoute: typeof AuthenticatedClientesIndexRoute
  AuthenticatedNpsIndexRoute: typeof AuthenticatedNpsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminMetricasRoute: AuthenticatedAdminMetricasRoute,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedKanbanRoute: AuthenticatedKanbanRoute,
  AuthenticatedMinhaRotinaRoute: AuthenticatedMinhaRotinaRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedClientesClienteIdRoute: AuthenticatedClientesClienteIdRoute,
  AuthenticatedNpsDetratoresRoute: AuthenticatedNpsDetratoresRoute,
  AuthenticatedNpsLinksRoute: AuthenticatedNpsLinksRoute,
  AuthenticatedNpsRespostasRoute: AuthenticatedNpsRespostasRoute,
  AuthenticatedClientesIndexRoute: AuthenticatedClientesIndexRoute,
  AuthenticatedNpsIndexRoute: AuthenticatedNpsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  NpsFormSlugRoute: NpsFormSlugRoute,
  ApiPublicHooksNpsRoute: ApiPublicHooksNpsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
